/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package volkswagegroup_is;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author OMEN
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    String path;
    
    public Register() {
        initComponents();
        reg_password.setEchoChar('\u25CF');
        reg_confirmpassword.setEchoChar('\u25CF');
        
        path = "register.txt";
        File registerobj = new File(path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reg_username = new javax.swing.JTextField();
        reg_confirmpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back_reg = new javax.swing.JButton();
        reg_password = new javax.swing.JPasswordField();
        register_details = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 195, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(107, 195, 234));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");

        reg_username.setBackground(new java.awt.Color(107, 195, 234));
        reg_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reg_username.setForeground(new java.awt.Color(255, 255, 255));
        reg_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        reg_confirmpassword.setBackground(new java.awt.Color(107, 195, 234));
        reg_confirmpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reg_confirmpassword.setForeground(new java.awt.Color(255, 255, 255));
        reg_confirmpassword.setText("Password");
        reg_confirmpassword.setToolTipText("Hint: admin");
        reg_confirmpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        reg_confirmpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        reg_confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_confirmpasswordFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirm Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        back_reg.setBackground(new java.awt.Color(107, 195, 234));
        back_reg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_reg.setForeground(new java.awt.Color(255, 255, 255));
        back_reg.setText("Back to Log In");
        back_reg.setToolTipText("");
        back_reg.setActionCommand("");
        back_reg.setBorder(null);
        back_reg.setContentAreaFilled(false);
        back_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_regMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back_regMouseExited(evt);
            }
        });
        back_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_regActionPerformed(evt);
            }
        });

        reg_password.setBackground(new java.awt.Color(107, 195, 234));
        reg_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reg_password.setForeground(new java.awt.Color(255, 255, 255));
        reg_password.setText("Password");
        reg_password.setToolTipText("Hint: admin");
        reg_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        reg_password.setCaretColor(new java.awt.Color(255, 255, 255));
        reg_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_passwordFocusGained(evt);
            }
        });

        register_details.setBackground(new java.awt.Color(107, 195, 234));
        register_details.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        register_details.setForeground(new java.awt.Color(255, 255, 255));
        register_details.setText("Register");
        register_details.setToolTipText("");
        register_details.setActionCommand("");
        register_details.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        register_details.setContentAreaFilled(false);
        register_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                register_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                register_detailsMouseExited(evt);
            }
        });
        register_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_detailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(back_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(100, 100, 100)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reg_confirmpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(register_details, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg_username)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(reg_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(register_details, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(64, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(64, 30));

        jMenu1.setText("File");

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Method for changing the property of confirm password text field when there is focus in it.
    */  
    private void reg_confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_confirmpasswordFocusGained
        // TODO add your handling code here:
            if(String.valueOf(reg_confirmpassword.getPassword()).trim().equals("Password")) {
            reg_confirmpassword.setText("");
        }
    }//GEN-LAST:event_reg_confirmpasswordFocusGained
    /*
    * Method for changing the property of password text field when there is focus in it.
    */
    private void reg_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_passwordFocusGained
        // TODO add your handling code here:
            if(String.valueOf(reg_password.getPassword()).trim().equals("Password")) {
            reg_password.setText("");
        }
    }//GEN-LAST:event_reg_passwordFocusGained
    /*
    * Method for changing the property of back to login button when mouse enters the hover area of it.
    */
    private void back_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_regMouseEntered
        // TODO add your handling code here:
        back_reg.setForeground(new Color(0, 90, 110));
    }//GEN-LAST:event_back_regMouseEntered
    /*
    * Method for changing the property of back to login button when mouse leaves the hover area of it.
    */
    private void back_regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_regMouseExited
        // TODO add your handling code here:
        back_reg.setForeground(Color.white);
    }//GEN-LAST:event_back_regMouseExited
    /*
    * Method for changing the property of back to login button when it is clicked
    */
    private void back_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_regMouseClicked
        // TODO add your handling code here:
        back_reg.setForeground(new Color(166, 227, 255));
    }//GEN-LAST:event_back_regMouseClicked
    /*
    * Method for changing the property of register button when it is clicked
    */
    private void register_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_detailsMouseClicked
        // TODO add your handling code here:
        register_details.setForeground(new Color(166, 227, 255));
    }//GEN-LAST:event_register_detailsMouseClicked
    /*
      *Method for changing the property of register button when mouse enters the hover area of it.
     */
    private void register_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_detailsMouseEntered
        // TODO add your handling code here:
        register_details.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(0, 90, 135)));
        register_details.setForeground(new Color(0, 90, 110));
    }//GEN-LAST:event_register_detailsMouseEntered
    /*
     * Method for changing the property of register button when mouse leaves the hover area of it.
     */
    private void register_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_detailsMouseExited
        // TODO add your handling code here:
        register_details.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white));
        register_details.setForeground(Color.white);
    }//GEN-LAST:event_register_detailsMouseExited

    /*
     * Method for closing the current frame
     */
    private void back_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_regActionPerformed
        // TODO add your handling code here:
        close();
        
    }//GEN-LAST:event_back_regActionPerformed
    /*
     * Method for registering the details of the user
     */
    private void register_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_detailsActionPerformed
        
        try {
            // TODO add your handling code here:
            String username = reg_username.getText();
            String password = String.valueOf(reg_password.getPassword());
            String cpassword = String.valueOf(reg_confirmpassword.getPassword());
            BufferedWriter out = new BufferedWriter(new FileWriter(new File("register.txt"), true)); //opening te register file to add the user details
            if(password.equals(cpassword) && !username.equals(""))
            {
                out.write(username + ", " + password + "\n");
                JOptionPane.showMessageDialog(rootPane , username + " has been successfully registered");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane , "Username empty or Password does not match");
            }
            out.close();
        } catch (IOException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_register_detailsActionPerformed
    /*
    * Method for closing the whole program
    */
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed
    /*
    * Method for opening help file when about menu item is clicked
    */
    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        File f = new File("help.pdf");
        Desktop desktop = Desktop.getDesktop();  
        try {
            desktop.open(f);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton back_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField reg_confirmpassword;
    private javax.swing.JPasswordField reg_password;
    private javax.swing.JTextField reg_username;
    private javax.swing.JButton register_details;
    // End of variables declaration//GEN-END:variables

    /*
     * Method for closing the current frame
     */
    private void close() {
        WindowEvent closeWindow=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
}

